### ISSUE TITLE
v1.0.0 Roadmap

### ISSUE THREAD

**Issue by SystematicError** [SystematicError/frosty-vim#1]
PS: This list is a bit out of date, will fix once finishing the rewrite

- [ ] Update Neovim to v0.10
    - [x] Update inputs
    - [x] Remove commentary
    - [x] Setup inlay hints
    - [ ] Add [satellite](https://github.com/lewis6991/satellite.nvim)
    - [x] Add [dropbar](https://github.com/Bekaboo/dropbar.nvim)
- [ ] Better modularisation
    - [x] Restrict modules to exporting only one plugin
    - [x] Allow modules to export keymaps
    - [x] Allow modules to export highlight overrides
    - [x] Allow modules to export colorscheme integrations
    - [ ] Sort out messy dependency structures
- [ ] Enhance appearance
    - [ ] Refine colorscheme pallete
    - [ ] Overhaul bufferline
    - [ ] Overhaul statusline
- [ ] Better direnv integration
    - [ ] Rewrite in lua
    - [ ] Notify / Indicate direnv state
- [ ] Improve terminal UX
- [ ] Improve fold UX
- [ ] Add more keymaps for commonly used commands
- [x] Non-nix compatibility
    - [x] Docker container for testing
- [ ] Lazy load all plugins
- [x] Nicer README.md
